server:
  port: 8079

spring:
  application:
    name: k2Pool-java-sdk

k2pool:
  #域名
  domain: http://127.0.0.1:8091
  #用户唯一标识
  accessKey: 3e4434699e1347ed8245813f8c96f64f

  aesKey: 51966658308f4b7d8eec99d67d4eec5b
  #token过期时间,单位分钟，默认30分钟
  tokenExpires: 10